"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

type Limit = "rpm" | "tpm" | "rpd" | "tpd";
type Row = { provider: "bai" | "gemini" | "nvidia"; model: string; credentialId: string; credentialLabel: string; projectId: string | null; quotaGroupId: string; used: Record<Limit, number>; limits: Record<Limit, number | null>; remaining: Record<Limit, number | null>; successes: number; errors: number; errors429: number; errors5xx: number; cooldownUntil: string | null; nextMinuteResetEstimate: string | null; nextDayReset: string | null; estimatedCostUsd: number; lastEventAt: string | null };
type Data = { ready: boolean; error: string | null; generatedAt: string; rows: Row[] };
const providers = new Set(["bai", "gemini", "nvidia"]);
const fmt = (value: number | null | undefined) => value == null ? "não informado" : Number(value).toLocaleString("pt-BR");
const time = (value: string | null) => value ? new Date(value).toLocaleString("pt-BR", { hour: "2-digit", minute: "2-digit", day: "2-digit", month: "2-digit" }) : "—";

export default function AiCapacityPage() {
    const [data, setData] = useState<Data | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");
    const load = useCallback(async () => {
        try { const response = await fetch("/api/admin/ai-capacity", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error || "Não foi possível carregar a capacidade."); setData({ ...payload, rows: (payload.rows || []).filter((row: Row) => providers.has(row.provider)) }); setError(""); } catch (cause: any) { setError(cause?.message || "Não foi possível carregar a capacidade."); } finally { setLoading(false); }
    }, []);
    useEffect(() => { void load(); }, [load]);
    const totals = useMemo(() => ({ requests: data?.rows.reduce((sum, row) => sum + row.used.rpm, 0) || 0, errors: data?.rows.reduce((sum, row) => sum + row.errors, 0) || 0, cooling: data?.rows.filter((row) => row.cooldownUntil && new Date(row.cooldownUntil) > new Date()).length || 0 }), [data]);
    return <div className="min-h-screen text-slate-100"><main className="mx-auto w-full max-w-7xl space-y-5 px-4 py-6 lg:px-6">
        <header className="flex flex-col gap-4 rounded-2xl border border-white/10 bg-white/[.035] p-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="admin-eyebrow">Central de IA</p><h1 className="admin-page-title">Capacidade ao vivo</h1><p className="admin-page-subtitle mt-2">Só B.AI, Gemini e NVIDIA. Veja quanto cada rota já usou e quando o router precisa esperar.</p></div><div className="flex gap-2"><Link href="/admin/ai" className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-semibold hover:bg-white/[.06]">Voltar para chaves</Link><button onClick={() => void load()} className="rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-bold text-slate-950">Atualizar</button></div></header>
        {error && <div className="rounded-xl border border-rose-300/25 bg-rose-300/[.08] p-4 text-sm text-rose-100">{error}</div>}
        {data && !data.ready && <div className="rounded-xl border border-amber-300/25 bg-amber-300/[.08] p-4 text-sm text-amber-100">A telemetria persistente ainda não está pronta: {data.error || "os números podem estar incompletos."}</div>}
        <section className="grid gap-3 sm:grid-cols-3"><Stat label="Requisições neste minuto" value={fmt(totals.requests)} /><Stat label="Rotas em pausa" value={String(totals.cooling)} tone="amber" /><Stat label="Erros registrados" value={fmt(totals.errors)} tone="rose" /></section>
        {loading ? <p className="admin-card p-8 text-center text-sm text-slate-500">Carregando capacidade...</p> : null}
        {!loading && data?.rows.length === 0 ? <p className="admin-card p-8 text-center text-sm text-slate-500">Ainda não há uso registrado. As rotas aparecem aqui após as primeiras mensagens.</p> : null}
        <section className="space-y-4">{data?.rows.map((row) => <article key={`${row.credentialId}-${row.model}`} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[.035]"><div className="flex flex-col gap-3 border-b border-white/10 p-5 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-cyan-300/10 px-2 py-1 text-[10px] font-bold uppercase text-cyan-100">{row.provider}</span><h2 className="font-semibold">{row.model}</h2></div><p className="mt-2 text-xs text-slate-500">{row.credentialLabel} · {row.projectId ? `Projeto: ${row.projectId}` : "Conta individual"} · Grupo: {row.quotaGroupId}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${row.cooldownUntil && new Date(row.cooldownUntil) > new Date() ? "bg-amber-300/10 text-amber-100" : "bg-emerald-300/10 text-emerald-100"}`}>{row.cooldownUntil && new Date(row.cooldownUntil) > new Date() ? `Pausada até ${time(row.cooldownUntil)}` : "Disponível"}</span></div><div className="grid gap-2 p-5 sm:grid-cols-2 lg:grid-cols-4">{(["rpm", "tpm", "rpd", "tpd"] as Limit[]).map((limit) => <div key={limit} className="rounded-xl border border-white/10 bg-black/20 p-3"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">{limit}</p><p className="mt-2 text-base font-semibold">{fmt(row.used[limit])} <span className="text-xs font-normal text-slate-500">usado</span></p><p className="mt-1 text-xs text-emerald-300">{row.remaining[limit] == null ? "limite não informado" : `${fmt(row.remaining[limit])} restante`}</p><p className="mt-1 text-[11px] text-slate-600">Limite: {fmt(row.limits[limit])}</p></div>)}</div><div className="grid gap-3 border-t border-white/10 bg-black/15 p-5 text-xs text-slate-400 sm:grid-cols-3"><p>Sucessos: <strong className="text-slate-200">{fmt(row.successes)}</strong> · Erros: <strong className="text-rose-200">{fmt(row.errors)}</strong></p><p>429: {fmt(row.errors429)} · 5xx: {fmt(row.errors5xx)}</p><p>Última atividade: {time(row.lastEventAt)}</p></div></article>)}</section>
        {data && <p className="pb-5 text-center text-xs text-slate-600">Atualizado em {time(data.generatedAt)} · Gemini compartilha quota por projeto.</p>}
    </main></div>;
}
function Stat({ label, value, tone = "cyan" }: { label: string; value: string; tone?: "cyan" | "amber" | "rose" }) { const color = { cyan: "text-cyan-100", amber: "text-amber-100", rose: "text-rose-100" }; return <div className="admin-card p-4"><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 text-2xl font-semibold ${color[tone]}`}>{value}</p></div>; }
